apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkins-vol
        hostPath:
          path: /var/lib/test_jenkins
      containers:
      - image: jenkins/jenkins:lts-jdk17
        name: jenkins
        volumeMounts:
        - name: jenkins-vol
          mountPath: /var/lib
        ports:
        - containerPort: 8080
        resources: {}
status: {}
