name: Docker image build
on:
  push:
    branches:
      - main
      - working-branch
    paths:
      - '**/app.py'
      - '**/Dockerfile'
      - '**/requirments.txt'
jobs:
  docker_version_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker Version Check
        run: |
          echo "Checking docker Version"
          docker version
      - name: Creating image tag
        run: |
          echo "Generating Docker image Tag"
          Image_tag=$(date +%Y%m)
          echo "$(Image_tag)"
  docker_build:
    runs-on: ubuntu-latest
    

  

