name: Docker image build
on:
  push:
    branches:
      - main
      - working-branch
    paths:
      - '**/app.py'
      - '**/Dockerfile'
      - '**/requirments.txt'
jobs:
  docker_version_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker Version Check
        run: |
          echo "Checking docker Version"
          docker version
      - name: Set Docker Image Tag
        id: set_tag
        run: |
          echo "Generating Docker image tag..."
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "::set-output name=image_tag::$IMAGE_TAG"

      # - name: Creating image tag
      #   run: |
      #     echo "Generating Docker image Tag"
      #     Image_tag=$(date +%Y%m)
      #     echo "$(Image_tag)"
  docker_build:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3



  

